### ISSUE TITLE
Search SBU dengan menggunakan NPWP yang masih baru daftar di LPJK

### ISSUE THREAD

**Issue by lodwig** [aalfiann/pbj#15]
Scenario jika ada SBU yang daftar di LPJK dan tidak pernah ikut tender di LPSE maka data tidak dapat di query.

Cara solvednya sepertinya dengan penambahan pengecekan jika belum ada di database maka akan query langsung ke LPJK dan insert ke database kita.

**Comment by aalfiann** [comment]
aa opan ga bs di assign nih, user nya ga muncul..wkwk..

kayanya belum di set `git config user.email "alamat@email.harus.sesuai.dgn.github.com"`

**Comment by aalfiann** [comment]
Done
